---
version: '2.3'

x-log-json: &log-json
  logging:
    driver: json-file
    options:
      max-file: "2"
      max-size: "50M"

services:
  lb:
    <<: *log-json
    image: ${DOCKER_REGISTRY}${REGISTRY_COMMON_STORAGE}nginx:${NGINX_VERSION}
    networks:
      - private

networks:
  private:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${LISTENER_SUBNET}
